blog/urls.py
from django.urls import path, re_path

from .views import *

app_name = 'blog'

urlpatterns = [
    path('testblog/',testblog,name='testblog'),
    path('load-more-blogs/', load_more_blogs, name='load_more_blogs'),
    path('about-us/', aboutus, name='about-us'),
    path('faq/', faq, name='faq'),
    path('blog/', blog, name='blog'),
    re_path(r'^blog-page/(?P<slug>.+)/$', blogpage, name='blogpage'),  # Allows any character

    path('create-blog/', PostCreate.as_view(), name='create-blog'),

    path('edit-blog/<int:id>/', PostEdit.as_view(), name='PostEdit'),

    path('blog/search/', PostSearchView.as_view(), name='search'),  # مسیر جستجو

    path('post-detail/<int:post_id>/', post_detail, name='post_detail'),

    path('delete-comment/<int:comment_id>/', delete_comment, name='delete_comment'),
    
    path('delete-blog/<int:id>/',delete_blog,name='delete_blog')



    # path('contact/', contact, name='contact'),

]

vakil/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users.views import robots_txt

from django.contrib.sitemaps.views import sitemap
from users.sitemap import StaticViewSitemap, ServiceSitemap, PostSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'services': ServiceSitemap,
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),  # مسیر چت را اضافه کنید

    path('', include('users.urls')),
    path('adminpanel/', include('users.admin.urls')),
    path('', include('service.urls')),
    path('', include('blog.urls')),

    path('payment/', include('payment.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('robots.txt', robots_txt, name='robots_txt'),

    path("sitemap.xml", sitemap, {'sitemaps': sitemaps}, name="sitemap"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.utils.timezone import now
from ckeditor.fields import RichTextField
from django.core.validators import RegexValidator
from users.models import Client


class Category(models.TextChoices):
    ANNOUNCEMENT = "announcement", "اطلاعیه و اخبار"
    LAW = "law", "قانون"
    EDUCATIONAL = "educational", "آموزشی"
    CASES = "cases", "پرونده‌های جذاب"


class SubCategory(models.TextChoices):
    CRIMINAL = "criminal", "کیفری"
    CIVIL = "civil", "حقوقی"
    FAMILY = "family", "خانواده"
    sabt = "sabt", "امور ثبتی"
    vaghf = "vaghf", "وقف و موقوفات"
    OTHER = "other", "سایر"


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = RichTextField()
    image = models.ImageField(upload_to="blog/posts")
    category = models.CharField(max_length=50, choices=Category.choices)
    subcategory = models.CharField(max_length=50, choices=SubCategory.choices, blank=True, null=True)
    slug = models.CharField(max_length=255, unique=True)
    author = models.ForeignKey(Client, on_delete=models.CASCADE)
    published_date = models.DateField(default=now)
    is_published = models.BooleanField(default=False)
    price = models.CharField(max_length=100, null=True, blank=True)
    summery = models.CharField(max_length=150, null=True, blank=True)
    view = models.IntegerField(default=0)
    time_to_read = models.IntegerField(default=10)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(Client, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    parent = models.OneToOneField('self', on_delete=models.CASCADE, null=True, blank=True, related_name="reply")

    def __str__(self):
        return f"Comment by {self.author} on {self.post}"

blog/views.py
from django.shortcuts import render

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from django.views import View
from .models import Post, Comment
from .form import *
from django.views.generic import ListView
from django.http import JsonResponse
from django.template.loader import render_to_string

# Create your views here.


def aboutus(request):
    return render(request, 'blog/about.html')


def faq(request):
    return render(request, 'blog/faq.html')


def blog(request):
    blog = Post.objects.filter(is_published=True)
    return render(request, 'blog/blog.html', {'blog': blog})



from django.db.models import F

def blogpage(request, slug):
    blog = get_object_or_404(Post, slug=slug)
    # افزایش تعداد بازدیدها با استفاده از F() برای جلوگیری از race condition
    Post.objects.filter(pk=blog.pk).update(view=F('view') + 1)
    related_posts = Post.objects.filter(category=blog.category, is_published=True).exclude(id=blog.id)[:5]
    
    return render(request, 'blog/blog-page.html', {
        'blog': blog,
        'related_posts': related_posts
    })


def contact(request):
    return render(request, 'blog/contact.html')


def post_list(request):
    posts = Post.objects.filter(is_published=True).order_by('-published_date')        
    return render(request, "blog/post_list.html", {"posts": posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.filter(parent__isnull=True)

    if request.method == "POST":
        form = CommentForm(request.POST)
            
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user

            # دریافت مقدار parent از فرم
            parent_id = request.POST.get("parent")
            if parent_id:
                try:
                    parent_comment = Comment.objects.get(id=parent_id)
                    comment.parent = parent_comment
                except Comment.DoesNotExist:
                    pass 

            comment.save()



            return redirect(request.META.get('HTTP_REFERER', 'blog:blogpage'))
    else:
        form = CommentForm()
    return render(request, "blog/faq.html", {"post": post, "comments": comments, "form": form})


@login_required
def approve_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user.is_staff:  # فقط ادمین
        comment.is_approved = True
        comment.save()
    return redirect("post_detail", slug=comment.post.slug)


@login_required
def reply_comment(request, comment_id):
    parent_comment = get_object_or_404(Comment, id=comment_id)
    if request.user.is_staff:  # فقط ادمین
        if request.method == "POST":
            content = request.POST.get("content")
            if content:
                Comment.objects.create(
                    post=parent_comment.post,
                    user=request.user.username,  # نام ادمین به عنوان نویسنده
                    content=content,
                    parent=parent_comment,
                    is_approved=True,
                )
                return redirect("post_detail", slug=parent_comment.post.slug)
        return render(request, "blog/reply_comment.html", {"comment": parent_comment})
    return redirect("post_detail", slug=parent_comment.post.slug)


def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user.is_staff:  # فقط ادمین
        comment.delete()    
    return redirect("blog:blogpage", slug=comment.post.slug)


class PostCreate(View):
    def get(self, request):
        if request.user.is_staff:
            form = PostForm()
            return render(request, 'blog/post_form.html', {'form': form})
        else:
            return redirect('users:login')

    def post(self, request):
        if request.user.is_staff:
            # ایجاد یک نسخه از فرم با داده‌های ارسالی
            form = PostForm(request.POST, request.FILES)
            
            if form.is_valid():
                post = form.save(commit=False)
                post.slug = post.title.lower().replace(' ', '-').replace('_', '-').replace('.', '-').strip('-')
                post.save()
                return redirect('blog:blog')
            else:
                print("فرم معتبر نیست. خطاها:")

            
            return render(request, 'blog/post_form.html', {"form": form})
        else:
            return redirect('users:login')


class PostEdit(View):
    def get(self, request, id):

        if request.user.is_staff:
            post = get_object_or_404(Post, id=id)
            form = PostForm(instance=post)
            return render(request, 'blog/post_form.html', {'form': form, 'post': post})
        else:
            return redirect('users:login')

    def post(self, request, id):
        if request.user.is_staff:
            post = get_object_or_404(Post, id=id)
            form = PostForm(request.POST, request.FILES, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                # اضافه کردن فیلدهای views و time_to_read
                post.save()
                print(1)
                return redirect('blog:blog')
            return render(request, 'blog/post_form.html', {'form': form, 'post': post})
        else:
            return redirect('users:login')


class PostSearchView(ListView):
    model = Post
    template_name = 'blog/search_results.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            # جستجو در عنوان و محتوا
            return Post.objects.filter(
                Q(title__icontains=query) | 
                Q(content__icontains=query),
                is_published=True
            ).order_by('-published_date')
        return Post.objects.none()


def delete_blog(request,id):
    if request.user.is_staff:
        post = get_object_or_404(Post, id=id)
        post.delete()
        return redirect('admin_blogs')
    else:
        return redirect('users:login')
    
    
def testblog(request):
    return render(request,'blog/bonyadvokala.html')


def load_more_blogs(request):
    if request.method == "GET":
        offset = int(request.GET.get("offset", 0))
        limit = 8
        blogs = Post.objects.filter(is_published=True).order_by('-published_date')[offset:offset+limit]
        html = render_to_string("blog/blog_list_partial.html", {"blogs": blogs})
        has_more = Post.objects.filter(is_published=True).count() > offset + limit
        return JsonResponse({"html": html, "has_more": has_more})
    return JsonResponse({"error": "Invalid request"}, status=400)

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% if post %}ویرایش مقاله{% else %}ایجاد مقاله جدید{% endif %}
{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <div class="card shadow-lg border-0">
                <div class="card-header bg-gold text-dark py-3">
                    <h3 class="text-center mb-0">
                        {% if post %}ویرایش مقاله: {{ post.title }}{% else %}ایجاد مقاله جدید{% endif %}
                    </h3>
                </div>
                <div class="card-body p-4 bg-blog text-light">
                    <form method="post" {% if post %}action="{% url 'blog:PostEdit' post.id %}" {% else
                        %}action="{% url 'blog:create-blog' %}" {% endif %} enctype="multipart/form-data"
                        class="form-rtl">
                        {% csrf_token %}

                        <div class="row mb-4">
                            <div class="col-md-12 mb-3">
                                <label for="{{ form.title.id_for_label }}" class="form-label fw-bold">عنوان
                                    مقاله:</label>
                                {{ form.title }}
                                <script>
                                    document.getElementById('{{ form.title.id_for_label }}').classList.add('form-control', 'bg-dark', 'text-light', 'border-secondary');
                                </script>
                                {% if form.title.errors %}
                                <div class="text-danger mt-1">{{ form.title.errors }}</div>
                                {% endif %}
                            </div>

                            <div class="col-md-12 mb-3">
                                <label for="{{ form.author.id_for_label }}" class="form-label fw-bold">نویسنده:(نام پنل
                                    نمایش داده میشود)</label>
                                {{ form.author }}

                                {% if form.author.errors %}
                                <div class="text-danger mt-1">{{ form.author.errors }}</div>
                                {% endif %}
                            </div>

                            <div class="col-md-12 mb-3">
                                <label for="{{ form.image.id_for_label }}" class="form-label fw-bold">تصویر
                                    شاخص:</label>
                                {{ form.image }}
                                <script>
                                    document.getElementById('{{ form.image.id_for_label }}').classList.add('form-control', 'bg-dark', 'text-light', 'border-secondary');
                                </script>
                                {% if form.image.errors %}
                                <div class="text-danger mt-1">{{ form.image.errors }}</div>
                                {% endif %}
                                {% if post and post.image %}
                                <div class="mt-2">
                                    <p>تصویر فعلی:</p>
                                    <img src="/media/{{ post.image }}" alt="تصویر فعلی" class="img-thumbnail"
                                        style="max-height: 150px;">
                                </div>
                                {% endif %}
                            </div>

                            <div class="col-md-12 mb-3">
                                <label for="{{ form.category.id_for_label }}"
                                    class="form-label fw-bold">دسته‌بندی:</label>
                                {{ form.category }}
                                <script>
                                    document.getElementById('{{ form.category.id_for_label }}').classList.add('form-control', 'bg-dark', 'text-light', 'border-secondary');
                                </script>
                                {% if form.category.errors %}
                                <div class="text-danger mt-1">{{ form.category.errors }}</div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="mb-4">
                            <label for="{{ form.content.id_for_label }}" class="form-label fw-bold">محتوای
                                مقاله:</label>
                            <div class="ckeditor-container bg-white p-2 rounded">
                                {{ form.media }}
                                {{ form.content }}
                            </div>
                            {% if form.content.errors %}
                            <div class="text-danger mt-1">{{ form.content.errors }}</div>
                            {% endif %}
                        </div>

                        <div class="row mb-4">
                            <div class="col-md-6 mb-3">
                                <label for="{{ form.subcategory.id_for_label }}" class="form-label fw-bold">زیر
                                    دسته‌بندی:</label>
                                {{ form.subcategory }}
                                <script>
                                    document.getElementById('{{ form.subcategory.id_for_label }}').classList.add('form-control', 'bg-dark', 'text-light', 'border-secondary');
                                </script>
                                {% if form.subcategory.errors %}
                                <div class="text-danger mt-1">{{ form.subcategory.errors }}</div>
                                {% endif %}
                            </div>

                            <div class="col-md-6 mb-3">
                                <label for="{{ form.published_date.id_for_label }}" class="form-label fw-bold">تاریخ
                                    انتشار:</label>
                                {{ form.published_date }}
                                <script>
                                    document.getElementById('{{ form.published_date.id_for_label }}').classList.add('form-control', 'bg-dark', 'text-light', 'border-secondary');
                                </script>
                                {% if form.published_date.errors %}
                                <div class="text-danger mt-1">{{ form.published_date.errors }}</div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="row mb-4">
                            <div class="col-md-6 mb-3">
                                <label for="{{ form.price.id_for_label }}" class="form-label fw-bold">قیمت:</label>
                                {{ form.price }}
                                <script>
                                    document.getElementById('{{ form.price.id_for_label }}').classList.add('form-control', 'bg-dark', 'text-light', 'border-secondary');
                                </script>
                                {% if form.price.errors %}
                                <div class="text-danger mt-1">{{ form.price.errors }}</div>
                                {% endif %}
                            </div>

                            <div class="col-md-6 mb-3">
                                <label for="{{ form.summery.id_for_label }}" class="form-label fw-bold">خلاصه
                                    مقاله:</label>
                                {{ form.summery }}
                                <script>
                                    document.getElementById('{{ form.summery.id_for_label }}').classList.add('form-control', 'bg-dark', 'text-light', 'border-secondary');
                                </script>
                                {% if form.summery.errors %}
                                <div class="text-danger mt-1">{{ form.summery.errors }}</div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-md-6 mb-3">
                                <label for="{{ form.view.id_for_label }}" class="form-label fw-bold">تعداد
                                    بازدید:</label>
                                {{ form.view }}
                                <script>
                                    document.getElementById('{{ form.views.id_for_label }}').classList.add('form-control', 'bg-dark', 'text-light', 'border-secondary');
                                </script>
                                {% if form.views.errors %}
                                <div class="text-danger mt-1">{{ form.views.errors }}</div>
                                {% endif %}
                            </div>

                            <div class="col-md-6 mb-3">
                                <label for="{{ form.time_to_read.id_for_label }}" class="form-label fw-bold">زمان مطالعه
                                    (دقیقه):</label>
                                {{ form.time_to_read }}
                                <script>
                                    document.getElementById('{{ form.time_to_read.id_for_label }}').classList.add('form-control', 'bg-dark', 'text-light', 'border-secondary');
                                </script>
                                {% if form.time_to_read.errors %}
                                <div class="text-danger mt-1">{{ form.time_to_read.errors }}</div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-6 mb-3">
                                <label for="{{ form.is_published.id_for_label }}" class="form-label fw-bold">وضعیت
                                    انتشار:</label>
                                <div class="form-check form-switch">
                                    {{ form.is_published }}
                                    <label class="form-check-label" for="{{ form.is_published.id_for_label }}">
                                        منتشر شود
                                    </label>
                                </div>
                                {% if form.is_published.errors %}
                                <div class="text-danger mt-1">{{ form.is_published.errors }}</div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-4">
                            <a href="{% url 'blog:blog' %}" class="btn btn-secondary me-md-2">انصراف</a>
                            <button type="submit" class="btn bg-gold text-dark fw-bold">
                                {% if post %}به‌روزرسانی مقاله{% else %}ایجاد مقاله{% endif %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block style %}
<style>
    .form-rtl {
        direction: rtl;
        text-align: right;
    }

    .ckeditor-container {
        border: 1px solid #444;
        border-radius: 5px;
    }

    /* تنظیمات برای CKEditor */
    .django-ckeditor-widget {
        width: 100% !important;
    }

    #cke_id_content {
        width: 100% !important;
        border: none !important;
    }

    /* رنگ‌بندی فرم‌ها */
    .form-control:focus {
        border-color: #ffc107;
        box-shadow: 0 0 0 0.25rem rgba(255, 193, 7, 0.25);
    }

    /* دکمه‌های سوییچ */
    .form-check-input:checked {
        background-color: #ffc107;
        border-color: #ffc107;
    }
</style>
{% endblock %}

{% block script %}
<script>
    document.getElementById('{{ form.author.id_for_label }}').classList.add('form-control', 'bg-dark', 'text-light', 'border-secondary');

    // اضافه کردن قابلیت جستجو به فیلد نویسنده
    $(document).ready(function () {
        $('#{{ form.author.id_for_label }}').select2({
            theme: 'bootstrap4',
            placeholder: 'جستجوی نویسنده...',
            allowClear: true,
            language: {
                noResults: function () {
                    return "نتیجه‌ای یافت نشد";
                }
            }
        });
    });
    document.addEventListener('DOMContentLoaded', function () {
        // اضافه کردن کلاس به المان‌های فرم برای زیباسازی
        document.querySelectorAll('select').forEach(function (select) {
            select.classList.add('form-select');
        });

        document.querySelectorAll('input[type="checkbox"]').forEach(function (checkbox) {
            checkbox.classList.add('form-check-input');
        });

        // تنظیم ارتفاع ادیتور
        setTimeout(function () {
            var iframe = document.querySelector('.cke_wysiwyg_frame');
            if (iframe) {
                iframe.style.height = '400px';
            }
        }, 1000);
    });
</script>
{% endblock %}